services:
    LeTots\MakeBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Bundle\MakerBundle\Generator: '@maker.generator'